spring.application.name: test.publisher
server.port: 6667

spring.rabbitmq.host: localhost
spring.rabbitmq.username: guest
spring.rabbitmq.password: guest

mongo.userName: admin
mong.credDb: admin
mongo.dataDb: kaarmadb
mongo.password: password
mongo.replicaHost1: mongo
mongo.replicaHost2: mongo
mongo.replicaPort1: 27011
mongo.replicaPort2: 27012
mongo.arbiterHost: mongo
mongo.arbiterPort: 27013
mongo.W: 1
mongo.J: true
mongo.fsync: true
mongo.connectionsPerHost: 8
mongo.connectTimeout: 20000
mongo.maxWaitTime: 20000
mongo.socketKeepAlive: true
mongo.socketTimeout: 30000
mongo.threadsAllowedToBlockForConnectionMultiplier: 4
